# Header
# menu:
#   Блог:    blog/
#   Архив:   archives/
#   Проекты: projects/

footer_menu:
  GitHub:  https://github.com/zb3k/devhook.net
  Roadmap: /todo/
  UI:      /ui/


lang: ru

# rss: /atom.xml

# Content
# excerpt_link: Read More
# src: true

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# # Miscellaneous
# google_analytics:
# favicon: /favicon.png
# twitter:
# google_plus:
# fb_admins:
# fb_app_id: