# Header
menu:
  Archives: archives/

footer_menu:
  ToDo: /todo/
  GitHub: https://github.com/zb3k/devhook.net

# rss: /atom.xml

# Content
# excerpt_link: Read More
src: true

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# # Miscellaneous
# google_analytics:
# favicon: /favicon.png
# twitter:
# google_plus:
# fb_admins:
# fb_app_id: